### ISSUE TITLE
V1.4.0 Uncaught TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by ericzorn93** [single-spa/single-spa-layout#114]
Dear Single Spa Layout Maintainers,

When bootstrapping a new Single SPA Root Config Application, utilizing Single SPA Layout as of v1.4.0, a type error has been thrown for trying to construct a URL object with the appropriate route paths. This is currently happening with the default EJS file configuration with the Single SPA Demo Application being added to the import map and as a default fallback.

However, this error also persists when running your root config app that is loading in your micro app bundles either over localhost in the local import map and/or from a hosted import map.

This error does not currently seem to be affecting functionality of your root-config or micro app. Just was hoping to have this error removed.

Images attached from vanilla CLI bootstrapped project (no changes or additions).

* When downgrading one minor version to 1.3.x, this error does **NOT** appear

Thank you,
Eric

![SingleSPA Layout Engine v 14 0 URL Constructor Error](https://user-images.githubusercontent.com/22532542/107059425-c5c0a900-67a3-11eb-84e3-b9b42630288f.png)

**Comment by ericzorn93** [comment]
May be from a chrome extension. Will reopen if I can reproduce.

**Comment by joeldenning** [comment]
Hi @ericzorn93, my guess about what would cause this issue is if you're not using the latest version of single-spa in your import map. Note that it's the version of single-spa in the import map in the index.ejs file of your root config that matters - not the package.json version. The reason that this would cause the error is that single-spa-layout assumes that `evt.detail.oldUrl` and `evt.detail.newUrl` are defined on routing events, but they were only introduced in https://github.com/single-spa/single-spa/releases/tag/v5.7.0. single-spa-layout@1.4.0 started calling `new URL()` because that was needed to fix a couple bugs. See https://github.com/single-spa/single-spa-layout/pull/106/files#diff-45b83d99dcd0b64a6370843b6833286a554ad98c3bf27bb91b8325fcfed78c78R416.

**Comment by ericzorn93** [comment]
Thank you for clarifying @joeldenning. I will update as soon as I confirm what version of SingleSPA I am using shortly.

**Comment by ericzorn93** [comment]
@joeldenning, this fixed the issue. I was running 5.5.0 accidentally. Thank you for your help

**Comment by joeldenning** [comment]
👍  glad to hear you got it working.
