### ISSUE TITLE
layout-engine causes the entire page to re-render if a microfrontend implements a sub-router

### ISSUE THREAD

**Issue by nilzona** [single-spa/single-spa-layout#126]
I have created this repo to describe and reproduce the problem

https://github.com/nilzona/layout-engine-issue

**Comment by joeldenning** [comment]
Hi @nilzona, thanks for providing the demonstration. I cloned the repo and tried it out today, but was unable to reproduce the problem. When I click on the Home/About/Topics links, it does not reload the page and everything seems to route properly (the header text changes properly).

Perhaps I'm misunderstanding what the problem is? Could you confirm if the problem is still present, and describe it to me in more detail?

**Comment by nilzona** [comment]
You will have to open the devtools and look at how the dom re-renders

**Comment by joeldenning** [comment]
Ah I see - the description originally said page reload so I thought that was the issue. I'll take a look at the re-renders.

**Comment by joeldenning** [comment]
I've put together a fix at #127. Thanks for providing the demonstration - it was very helpful. We were indeed doing a bunch of unnecessary work that potentially was resulting in unnecessary repaints/reflows. I've explained in more detail in the PR if you're interested.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.5.2
