### ISSUE TITLE
Error parcel of MFE1 (previous) is not removed while loader parcel of MFE2 (current) is shown

### ISSUE THREAD

**Issue by vmizg** [single-spa/single-spa-layout#137]
Problem context:

In our case, we have set up two mfes: `@mfe/one` and `@mfe/two`. Both have a `loader` and an `error` parcel passed to single-spa-layout when doing `constructRoutes` and registered in HTML. (single-spa-layout version **1.5.3**)

Suppose that now `@mfe/one` throws due to whatever reason.

Since it's thrown, we can't do much but navigate away somewhere. Using react-router-dom, we navigate to a different path where `@mfe/two` is registered. Upon navigation to `@mfe/two`, while single-spa imports the relevant mfe, *both* the loader parcel for the new mfe and the error parcel for `@mfe/one` are displayed. The URL has already changed to the path of `@mfe/two` at that point.

See a visual representation of the issue:
![singlespa-weird](https://user-images.githubusercontent.com/9007308/122349853-39a76500-cf7f-11eb-9733-970c84cf15ad.png)

This behaviour only continues to happen for a blink of a second due to the fact that serving (resolving) a new mfe does not take that long. As such I was able to replicate this behaviour properly by setting up an extended timeout inside the `loadApp` Promise.

Let me know if you need any more details.

I've also left a comment under #105 earlier as I thought these might be related.

**Comment by joeldenning** [comment]
Single-spa-layout calls the `unmount()` lifecycle for the error parcel during [single-spa:before-routing-event](https://single-spa.js.org/docs/api#before-routing-event). The unmount lifecycle returns a promise and may take some time; however, single-spa/single-spa-layout do not wait for the unmount lifecycle's promise to resolve to proceed to mounting.

This is something that should be fixed, and I think the best approach is to mount the error parcel as an application parcel, rather than a root parcel, since application parcels are automatically unmounted when an application is unmounted, including waiting for the application parcel to fully finish unmounting. However, there's a problem with that approach since applications in LOAD_ERROR state are not unmounted (nor their application parcels), and also because applications are automatically unmounted when they fail to mount.

So another solution could be to mark the application for unloading, and then unmount the error parcel during its unload lifecycle. I think that's the best approach, probably, and will work on an implementation for it this morning.

**Comment by joeldenning** [comment]
The implementation approaches above didn't work out, but I found a different one that does work, in #138

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.6.0
