### ISSUE TITLE
Webpack module federation issue with single-spa default import

### ISSUE THREAD

**Issue by jtrujill** [single-spa/single-spa-layout#141]
I've been having issues with using single-spa-layout with webpack's module federation plugin. I've tracked the issue down to the file `src/isomorphic/constructRoutes.js`. The import `import * as singleSpa from "single-spa";` is the root of the cause. 

I'm using es modules and webpack's runtime is checking to see if the single-spa module is an esModule and if it is it's making a call to get the exported function named `default`. Because single-spa doesn't have a default export the value is undefined. This causes things to blow up when it tries to get the `pathToActiveWhen` method. 

There's a comment that was left in the code and I'm not sure I understand the reason that single-spa is being imported that way. When I change the import to a named import pulling in `pathToActiveWhen` directly it resolves my issue. Do we know when this import issue would be resolved?

**Comment by jtrujill** [comment]
To give more context I'll include a test project I'm working on https://github.com/jtrujill/front_end_prototype. To be clear this issue only occurs when I try to share single-spa. If I use the following for`webpack.common.js` I don't have issues

```
const path = require("path");
const webpack = require("webpack");
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");

const { "single-spa": singleSpa, ...deps } = require("./package.json").dependencies;

const environment = (process.env.ENV || "").toLocaleLowerCase();

function getEnvironmentFile(env) {
  const baseFilename = "environment";

  let envFile;
  switch (environment) {
    case "prod":
      envFile = `${baseFilename}.prod.ts`;
      break;
    default:
      envFile = `${baseFilename}.ts`;
  }
  return path.resolve(__dirname, "src", "environments", envFile);
}

module.exports = {
  entry: path.join(__dirname, "src", "index.tsx"),
  output: {
    publicPath: "auto",
    uniqueName: "shell",
    filename: "shell.js",
    path: path.join(__dirname, "dist"),
    devtoolNamespace: "shell",
  },
  plugins: [
    new ModuleFederationPlugin({
      remotes: {
        login: "login@http://localhost:3004/remoteEntry.js",
        mainMenu: "mainMenu@http://localhost:3003/remoteEntry.js",
        orders: "orders@http://localhost:3002/remoteEntry.js",
        practices: "practices@http://localhost:3001/remoteEntry.js",
      },
      shared: {
        ...deps,
        "single-spa-react": { singleton: true, requiredVersion: deps["single-spa-react"] },
        "single-spa-layout": { singleton: true, requiredVersion: deps["single-spa-layout"] },
        react: { singleton: true, requiredVersion: deps.react },
        "react-dom": { singleton: true, requiredVersion: deps.react },
        "react-use": {
          singleton: true,
          requiredVersion: deps["react-use"],
        },
      },
    }),
    new webpack.NormalModuleReplacementPlugin(/environments\/environment/, getEnvironmentFile(environment)),
    new HtmlWebpackPlugin({ inject: true, template: "./public/index.html" }),
  ],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"],
      },
      {
        test: /\.tsx?/,
        loader: "ts-loader",
        exclude: /node_modules/,
        options: {
          transpileOnly: true,
        },
      },
    ],
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js", ".css"],
  },
};

```

**Comment by jtrujill** [comment]
If the propertyDescriptor for default is defined it looks like you need to access it through the get method rather than through value. I'm not too familiar with this so would this be in all cases or is my case unique?

**Comment by joeldenning** [comment]
> There's a comment that was left in the code and I'm not sure I understand the reason that single-spa is being imported that way. 

Single-spa publishes both in UMD and ESM format. However, it currently does not have an `"exports"` field in the package.json, nor is its `"type"` field set to `"module"`. Because of this, NodeJS defaults to using the UMD version (since it's the `"main"` field in the package.json), and since it's a nodejs runtime environment the UMD build operates as a commonjs bundle. When ESM nodejs code imports a commonjs module, it receives just a single default export, rather than all of its named exports. For that reason, proper usage of single-spa@5 in ESM nodejs code is `import singleSpa from 'single-spa'; singleSpa.registerApplication();`. This was recently helped by the recent PR to NodeJS that lexes the code to try to find named exports. However, that is only for newest versions of Node, and is not guaranteed to work for all cases.

For all other environments (webpack/rollup/CJS code in Node), single-spa does not have a default export but rather has named exports.

Coming back to this code:

https://github.com/single-spa/single-spa-layout/blob/50b691858e172366eb9758cfb1d5a30d99c6c5ca/src/isomorphic/constructRoutes.js#L12

https://github.com/single-spa/single-spa-layout/blob/50b691858e172366eb9758cfb1d5a30d99c6c5ca/src/isomorphic/constructRoutes.js#L18-L24

We're doing `import * as singleSpa from 'single-spa' to avoid having to decide at build time whether we're going to access single-spa's functions via a default export or named exports. Then at runtime, we check whether to use the default export or named export.

Unfortunately, it's not that simple, though, because we're using rollup to bundle single-spa-layout, and rollup has optimizations that try really hard to tree shake and not let you import the whole module. The `getOwnPropertyDescriptor` workaround was the only way I could find to get rollup to leave the `import * as singleSpa from 'single-spa';` alone without tree shaking it.

The best solution would be just to release a new major version of single-spa that has `"exports"` set, so that nodejs and webpack/rollup code paths can be different such that all of this workaround is unnecessary. I'll submit a PR to single-spa to do so.

**Comment by jtrujill** [comment]
Thanks Joel I really appreciate yours and others hard work on these libraries

**Comment by joeldenning** [comment]
I've made some progress on the changes I want to include in single-spa@6, including adding `"exports"` to the package.json which will solve this. Hope to have a PR up for it in the next few days

**Comment by joeldenning** [comment]
I released https://github.com/single-spa/single-spa-layout/releases/tag/v2.0.0-beta.0, which can be installed via `npm install single-spa-layout@beta`. That version uses a version of single-spa that has package entrypoints, so I think it should solve your problem. Let me know if it does!
