### ISSUE TITLE
Can't use single-spa-layout/server with typescript 4.5

### ISSUE THREAD

**Issue by lipsumar** [single-spa/single-spa-layout#155]
When trying to use `single-spa-layout/server` with typescript 4.5 and node 16.4, typescript reports an error when building:

```
index.ts:3:8 - error TS7016: Could not find a declaration file for module 'single-spa-layout/server'. '/Users/emmanuelpire/dev/single-spa-layout-ts-issue/node_modules/single-spa-layout/dist/umd/single-spa-layout-server.min.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/single-spa-layout` if it exists or add a new declaration (.d.ts) file containing `declare module 'single-spa-layout/server';`
```

As said in https://github.com/single-spa/single-spa-layout/issues/145, Typescript and node must support [package entrypoints](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packages_package_entry_points), which is the case for typescript 4.5 and node 16. 

This issue is reproduced in this repo: https://github.com/lipsumar/single-spa-layout-ts-issue

Steps to reproduce:
1. `yarn install`
2. `yarn build`

**Comment by lipsumar** [comment]
Also, the [API documentation](https://single-spa.js.org/docs/layout-api#constructserverlayout) says to import this way:

```ts
import { constructServerLayout } from 'single-spa-layout';
```

and the [SSR documentation](https://single-spa.js.org/docs/ssr-overview) says to import this way:

```ts
import { constructServerLayout } from 'single-spa-layout/server';
```

I believe the correct way is `from 'single-spa-layout/server'`.

**Comment by joeldenning** [comment]
I spent some time looking at this today - the reason you're required to do the dynamic import that you mentioned in #145 is because commonjs code cannot load ES module code via `require()`, which is the only way to synchronously load code inside of commonjs. So the only way to load ES module code inside of a commonjs file is with dynamic import(). In your tsconfig, you have set `module` to be `node12` which does not fully support for ES modules or package entrypoints, so typescript is compiling your project to commonjs to try to make it compatible with the output environment. You can read more about commonjs and esm interop at https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#interoperability-with-commonjs

I played around with your example project, changing some values in the tsconfig and in the node_modules, but was unable to get it working. I stripped the example all the way down to the simplest possible example and was unable to get typescript 4.5.0 to load the most basic package entrypoint. It is still looking at the single-spa-layout package.json `"types"` field rather than the `"exports"` field, even though exports is higher priority. Even when I removed the top-level `"types"` field from the single-spa-layout package.json, it still didn't read package entrypoints. So as far as I can tell, typescript@4.5.0 has no support for package entrypoints, or maybe it does but requires a special configuration combination in the tsconfig that I have not stumbled upon. I might look into this further later, but decided to pause because i'm catching up on several dozen github notifications. If you or someone else finds a solution, please post it here - I'm happy to make changes to single-spa-layout to support this but as far as I can tell typescript just doesn't really support package entrypoints.

**Comment by joeldenning** [comment]
Also, thanks for reporting the issue with the documentation import statement, I've fixed it in https://github.com/single-spa/single-spa.js.org/pull/499

**Comment by lipsumar** [comment]
Is there a version of typescript that can import `single-spa-layout/server` ? I tried with latest (4.4.4) and i get the following error:

```
TS2307: Cannot find module 'single-spa-layout/server' or its corresponding type declarations.
```

Is there a typescript version that's compatible, or is single-spa-layout/server not currently usable with typescript ?

I reproduced the typescript 4.4.4 setup in branch `ts-latest` of the repo: https://github.com/lipsumar/single-spa-layout-ts-issue/tree/ts-latest

**Comment by joeldenning** [comment]
There's no version that works with typescript - single-spa-layout publishes ES modules and uses package entrypoints, which are both things that typescript isn't good at supporting. I might have time some other day to look into this further, but would appreciate community contributions on it, too

**Comment by filoxo** [comment]
This might be worth reaching out to Jason Miller to see if someone could take him up on this offer: https://twitter.com/_developit/status/1460678262439530501

It may also be worth exploring if using tsm  (https://github.com/lukeed/tsm) for it's ESM loader capabilities could solve this problem too.

**Comment by tbrannam** [comment]
So `exports` and `typeVersions` are package.json values are fairly new to me, but it appears that this problem can be addressed by adding 
```
	"typesVersions": {
		"*": {
			"server": [
				"dist/types/single-spa-layout-server.d.ts"
			]
		}
	},
```

to the package.json of single-spa-layout - this fixed my type issues on importing,  now I just need to resolve the usage of `any` in the return values of the exported functions.

**Comment by Kinle** [comment]
@joeldenning Can you review this PR ? I have checked it with local file install and it works

**Comment by joeldenning** [comment]
I think this has been solved with https://github.com/single-spa/single-spa-layout/pull/187

**Comment by joeldenning** [comment]
#187 was released in https://github.com/single-spa/single-spa-layout/releases/tag/v2.2.0
