### ISSUE TITLE
Lazy Loading not working with JSON with mode as hash

### ISSUE THREAD

**Issue by lee9019** [single-spa/single-spa-layout#66]
[rootApp.zip](https://github.com/single-spa/single-spa-layout/files/5232609/rootApp.zip)

I type in url http://localhost:4200/#/subapp. It does not load sub app. All apps from json are loaded by default at start even if the apps have path property defined

**Comment by joeldenning** [comment]
Hi @lee9019, thanks for providing the zip file showing your code. I found a couple problems with the code:

1. You are calling `constructRoutes` with the wrong parameter.
2. Your index.html is missing ZoneJS, so the angular applications are failing to start up.

Regarding the first problem, you should only call constructRoutes once with the json config, instead of once per route. There were a lot of errors in the browser console indicating that this was the case.

### Incorrect code

System.import('single-spa-layout').then(function (layout) {
  fetch('./assets/props.json').then(function (response) {
    return response.json();
  })
    .then(function (props) {
      props.routes.forEach(route => {

        const routes = layout.constructRoutes(
          route
        );
        // const routes = layout.constructRoutes(document.querySelector("#single-spa-template"));
        const applications = layout.constructApplications({
          routes,
          loadApp({ name }) {
            return System.import(name);
          },
        });
        const layoutEngine = layout.constructLayoutEngine({
          routes,
          applications
        });
        System.import('single-spa').then(function (singlespa) {
          applications.forEach(singlespa.registerApplication);
          singlespa.start();
        })
      });
    });
});


### Correct code

```js
System.import('single-spa-layout').then(function (layout) {
  fetch('./assets/props.json').then(function (response) {
    return response.json();
  })
    .then(function (props) {
      const routes = layout.constructRoutes(
        props
      );
      // const routes = layout.constructRoutes(document.querySelector("#single-spa-template"));
      const applications = layout.constructApplications({
        routes,
        loadApp({ name }) {
          return System.import(name);
        },
      });
      const layoutEngine = layout.constructLayoutEngine({
        routes,
        applications
      });
      System.import('single-spa').then(function (singlespa) {
        applications.forEach(singlespa.registerApplication);
        singlespa.start();
      })
    });
});

```

**Comment by lee9019** [comment]
Yes. Thank you so much. The first one was the problem. It is working now. Also in history mode when I type url as http://localhost:4200/subapp it just refreshes, no application loaded with JSON. Any idea on this?

**Comment by joeldenning** [comment]
> Also in history mode when I type url as http://localhost:4200/subapp it just refreshes, no application loaded with JSON.

Are you typing this into the browser URL bar and then pressing enter? If so, the behavior of the browser is to refresh the page when you do that - there is nothing that can change that. However, clicking on links within the page, or performing programmatic navigation, should not result in the page being reloaded.

**Comment by lee9019** [comment]
I have links as  <a href="/subapp">subapp</a> and mode in props.json as history. I click it. it shows in browser as http://localhost:4200/subapp for few seconds and then goes back to http://localhost:4200. Not sure If I have done anything wrong. The code is the same attached only change mode from hash to history.

**Comment by joeldenning** [comment]
When you use an `<a>` element that changes the URL path (such as in history mode), it reloads the page by default. Frameworks like react/vue/angular will add a click listener that calls `event.preventDefault()` which prevents the page reload. In your case, the index.html file has `<a>` elements that do not call preventDefault. Normally we recommend using a framework router link component (such as `<Link>`, `<router-link>` etc) that does this all for you. Alternatively, you can use single-spa's `navigateToUrl` function, or `window.singleSpaNavigate()` which also call `preventDefault()`. One thing to note is that there are plans to add a `<single-spa-link>` component that calls navigateToUrl for you when using single-spa-layout.

[Documentation](https://single-spa.js.org/docs/api#navigatetourl)

[Example](https://codesandbox.io/s/hungry-snow-25sqi?file=/index.html)

**Comment by lee9019** [comment]
I tried like this as you suggested 
<a href="/subapp" onclick="singleSpaNavigate(event)">Link to app1</a>
still not happening. In consle error **main-es5.js:1 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'subapp'**

**Comment by joeldenning** [comment]
Could you please share the updated code for this? I can take a look to help diagnose.

**Comment by lee9019** [comment]
[rootapp.zip](https://github.com/single-spa/single-spa-layout/files/5259231/rootapp.zip)

**Comment by joeldenning** [comment]
Thanks for sharing the code - the problem was that singleSpaNavigate() was being called without the `event` argument.

Incorrect code:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/5524384/93913760-c4925200-fcc2-11ea-95c7-a984651cf43f.png">


Correct code:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/5524384/93913740-bc3a1700-fcc2-11ea-8b73-45d86276fd6d.png">

Once I fixed that, I got a new error from Angular about the `/subapp` route not being defined in Angular's router, which makes sense - all active applications must define routes for the current URL.

Another thing I'll add is that this project uses an iframe to contain the code, which is unusual and generally not preferred. It makes it harder to diagnose, since the URL in the browser doesn't change when the URL within the iframe changes.
