### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by alanquigley-toast** [single-spa/single-spa-layout#87]
JSX support was discussed early in the RFC but was eventually removed. I'm wondering if there is a fundamental problem with using JSX to construct the JSON object or was it removed to simplify the API for a broader audience?

**Comment by joeldenning** [comment]
Hi @alanquigley-toast - yes there was an initial implementation that used JSX, but it was abandoned in favor of the HTML or JSON approaches. The main reasons:

1. There was interest expressed in storing the layout config in a database, and JSON is better suited for that.
2. People who know React JSX well would not have been rewarded for their knowledge, since the single-spa-layout JSX worked somewhat differently. For example, the syntax for props was different: `<application props={{name: 'value'}}>` instead of `<application name="value">`. Also, the built-in components `<application>`, `<fragment>`, etc were lowercase which is not how normal react jsx expects components to be. Additionally, the element objects created by the JSX implementation were different than what you'd expect if you know React.
3. For server-side rendering, the layout must be processed on the backend but also serialized and sent to the browser. Serializing HTML and JSON is a lot more natural than than serializing JSX. Also, the layout must be inserted into a full HTML file at the correct location, and so using HTML is easier to do that than JSX inside of js that then must be inserted into an HTML template. The full HTML file includes much more than just the `<single-spa-router>` file. 

I'm not opposed to bringing JSX back, though. None of the above issues are unsolvable. We'd just need to find good answers for those problems and then implement it. If you have interest in helping with the implementation, I'd be happy to collaborate.

**Comment by alanquigley-toast** [comment]
Really appreciate the detail
